name: kaggle
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch-lightning=1.6.0
  - pytorch=1.9.1
  - torchaudio=0.9.1
  - torchtext=0.10.1
  - torchvision=0.10.1
  - tqdm=4.63.0
  - kaggle=1.5.12
  - dacite=1.6.0
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - PyYAML=6.0
  - matplotlib=3.5.2
